[package]
name = "synalpheus"

version = "0.10.1"
edition = "2024"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
futures = { version = "0.3", features = ["executor"] }
oauth2 = "5"
poem = { version = "3.1", features = [
    "session",
    "compression",
    "csrf",
    "multipart",
    "test",
    "static-files",
    "tower-compat"
] }
reqwest = { version = "0.13", features = ["json", "blocking"] }
sea-orm = { version = "2.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "mock",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["std"] }
tera = { version = "2.3", features = ["glob_fs", "fast"] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
toml = "1.1.4"
tower-http-cache = { version = "0.6.1", features = ["compression", "tracing"] }
