//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "application")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pk: String,
    pub name: String,
    pub slug: String,
    pub launch_url: String,
    pub icon: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        super::application_group::Relation::Group.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::application_group::Relation::Application.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
